[project]
name = "rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Sumayya", email = "umithayyil5@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "chromadb>=1.5.9",
    "faiss-cpu>=1.15.1",
    "ipykernel>=7.3.0",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.5",
    "networkx>=3.7",
    "openpyxl>=3.1.5",
    "pandas>=3.0.6",
    "pymupdf>=1.28.2",
    "pypdf>=6.19.0",
    "sentence-transformers>=6.1.0",
    "unstructured>=0.27.10",
]

[project.scripts]
rag = "rag:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
